import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'EN' | 'BN' | 'UR' | 'HI' | 'AR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    dashboard: 'Dashboard',
    invoices: 'Invoices',
    unpaid: 'Unpaid',
    apps: 'Apps Management',
    panels: 'Panels Management',
    decoders: 'Decoder Management',
    users: 'Users Management',
    pending_users: 'Pending Requests',
    finances: 'Investments',
    settings: 'Settings',
    logout: 'Logout',
    system: 'System',
    management_portal: 'Management Portal',
    master_admin: 'Master Admin',
    save_changes: 'Save All Changes',
    saving: 'Saving...',
    thank_you: 'Thank you for your business!',
    invoice_to: 'Invoice To:',
    invoice_no: 'INVOICE #',
    name: 'Name',
    phone: 'Phone',
    date: 'Date',
    txn_id: 'TXN ID',
    sl_no: 'SL.No.',
    item_description: 'Item Description',
    unit_price: 'Unit Price',
    quantity: 'Quantity',
    total: 'Total',
    bank_info: 'Bank Information',
    bank_name: 'Bank Name',
    branch_name: 'Branch Name',
    account_no: 'Account No',
    payment_status: 'Payment Status',
    terms_condition: 'Terms and Condition',
    sub_total: 'Sub Total',
    paid_amount: 'Paid Amount',
    due_balance: 'Due Balance',
    grand_total: 'Grand Total',
    scan_to_verify: 'Scan to Verify',
    financial_overview: 'Financial Overview',
    financial_summary: 'Summary of system revenue and latest logs',
    total_revenue: 'Total Revenue',
    total_investment: 'Total Investment',
    net_profit: 'Net Profit',
    pending_invoices_status: 'pending invoices',
    system_health: 'System Health',
    operational: 'Operational',
    revenue_stream: 'Revenue Stream',
    recent_invoices: 'Recent Invoices',
    recent_activities: 'Recent Activities',
    view_full_history: 'View Full History',
    no_invoices: 'No invoices found',
    invoice_management: 'Invoice Management',
    billing_records_desc: 'Billing, records, and due tracking',
    unpaid_invoices_desc: 'Viewing pending and overdue records',
    create_new_invoice: 'Create New Invoice',
    filter_invoices: 'Filter invoices...',
    id_date: 'ID / Date',
    source: 'Source',
    client_method: 'Client / Method',
    actions: 'Actions',
    status: 'Status',
    generating_pdf: 'Generating PDF...',
    please_wait_pdf: 'Please wait while we prepare your invoice',
    invoice_preview: 'Invoice Preview',
    prof_layout_desc: 'Professional layout for printing and sharing',
    download_pdf: 'Download PDF',
    preview_invoice: 'Preview Invoice',
    edit_invoice: 'Edit Invoice',
    delete_invoice: 'Delete Invoice',
    welcome_back: 'Welcome back to your workspace',
    username: 'Username',
    password: 'Password',
    enter_username: 'Enter username',
    enter_password: 'Enter Password',
    sign_in: 'Sign In',
    sign_in_google: 'Sign in with Google',
    invalid_credentials: 'Invalid username or password. Use admin / admin123',
    unexpected_error: 'An unexpected error occurred.',
    no_recent_activities: 'No recent activities found',
    understood: 'Understood',
    invoice_gen_desc: 'Invoice generation is linked to customer orders.',
    paid: 'Paid',
    pending: 'Pending',
    overdue: 'Overdue',
    unpaid_status: 'Unpaid',
    time: 'Time'
  },
  BN: {
    dashboard: 'ড্যাশবোর্ড ওভারভিউ',
    invoices: 'ইনভয়েস লিস্ট',
    unpaid: 'বাকি ইনভয়েস',
    apps: 'অ্যাপ ম্যানেজমেন্ট',
    panels: 'প্যানেল ম্যানেজমেন্ট',
    decoders: 'ডিকোডার ম্যানেজমেন্ট',
    users: 'ইউজার ম্যানেজমেন্ট',
    pending_users: 'নিবন্ধন অনুরোধসমূহ',
    finances: 'ইনভেস্টমেন্ট',
    settings: 'সিস্টেম সেটিংস',
    logout: 'লগআউট',
    system: 'সিস্টেম',
    management_portal: 'ম্যানেজমেন্ট পোর্টাল',
    master_admin: 'মাস্টার এডমিন',
    save_changes: 'সব পরিবর্তন সংরক্ষণ করুন',
    saving: 'সংরক্ষণ করা হচ্ছে...',
    thank_you: 'আমাদের সাথে ব্যবসা করার জন্য ধন্যবাদ!',
    invoice_to: 'প্রতি:',
    invoice_no: 'ইনভয়েস নং',
    name: 'নাম',
    phone: 'ফোন',
    date: 'তারিখ',
    txn_id: 'টিএক্সএন আইডি',
    sl_no: 'ক্রমিক নং',
    item_description: 'বিবরণ',
    unit_price: 'একক মূল্য',
    quantity: 'পরিমাণ',
    total: 'মোট',
    bank_info: 'ব্যাংক তথ্য',
    bank_name: 'ব্যাংকের নাম',
    branch_name: 'শাখার নাম',
    account_no: 'অ্যাকাউন্ট নং',
    payment_status: 'পেমেন্ট স্ট্যাটাস',
    terms_condition: 'শর্তাবলী',
    sub_total: 'সাব টোটাল',
    paid_amount: 'পরিশোধিত',
    due_balance: 'বাকি',
    grand_total: 'সর্বমোট',
    scan_to_verify: 'যাচাই করতে স্ক্যান করুন',
    financial_overview: 'আর্থিক ওভারভিউ',
    financial_summary: 'সিস্টেম রেভিনিউ এবং সর্বশেষ লগের সারসংক্ষেপ',
    total_revenue: 'মোট রেভিনিউ',
    total_investment: 'মোট ইনভেস্ট',
    net_profit: 'মোট প্রফিট',
    pending_invoices_status: 'বাকি ইনভয়েস',
    system_health: 'সিস্টেম হেলথ',
    operational: 'চলমান',
    revenue_stream: 'রেভিনিউ স্ট্রীম',
    recent_invoices: 'সাম্প্রতিক ইনভয়েস',
    recent_activities: 'সাম্প্রতিক কার্যক্রম',
    view_full_history: 'সম্পূর্ণ ইতিহাস দেখুন',
    no_invoices: 'কোনো ইনভয়েস পাওয়া যায়নি',
    invoice_management: 'ইনভয়েস ম্যানেজমেন্ট',
    billing_records_desc: 'বিলিং, রেকর্ড এবং বকেয়া ট্র্যাকিং',
    unpaid_invoices_desc: 'অপেক্ষমান এবং বকেয়া রেকর্ড দেখা হচ্ছে',
    create_new_invoice: 'নতুন ইনভয়েস তৈরি করুন',
    filter_invoices: 'ইনভয়েস ফিল্টার করুন...',
    id_date: 'আইডি / তারিখ',
    source: 'উৎস',
    client_method: 'ক্লায়েন্ট / পদ্ধতি',
    actions: 'অ্যাকশন',
    status: 'স্ট্যাটাস',
    generating_pdf: 'পিডিএফ তৈরি হচ্ছে...',
    please_wait_pdf: 'অনুগ্রহ করে অপেক্ষা করুন, ইনভয়েস প্রস্তুত হচ্ছে',
    invoice_preview: 'ইনভয়েস প্রিভিউ',
    prof_layout_desc: 'প্রিন্ট এবং শেয়ার করার জন্য পেশাদার লেআউট',
    download_pdf: 'পিডিএফ ডাউনলোড করুন',
    preview_invoice: 'ইনভয়েস প্রিভিউ',
    edit_invoice: 'ইনভয়েস এডিট করুন',
    delete_invoice: 'ইনভয়েস ডিলিট করুন',
    welcome_back: 'আপনার ওয়ার্কস্পেসে স্বাগতম',
    username: 'ইউজারনেম',
    password: 'পাসওয়ার্ড',
    enter_username: 'ইউজারনেম দিন',
    enter_password: 'পাসওয়ার্ড দিন',
    sign_in: 'সাইন ইন',
    sign_in_google: 'গুগল দিয়ে সাইন ইন',
    invalid_credentials: 'ইউজারনেম বা পাসওয়ার্ড সঠিক নয়। admin / admin123 ব্যবহার করুন',
    unexpected_error: 'একটি অপ্রত্যাশিত ত্রুটি ঘটেছে।',
    paid: 'পরিশোধিত',
    pending: 'অপেক্ষমান',
    overdue: 'বকেয়া',
    unpaid_status: 'বকেয়া',
    time: 'সময়'
  },
  UR: {
    dashboard: 'ڈیش بورڈ جائزہ',
    invoices: 'انوائس کی فہرست',
    unpaid: 'غیر ادا شدہ انوائس',
    apps: 'ایپ مینجمنٹ',
    panels: 'پینل مینجمنٹ',
    decoders: 'ڈیکوڈر مینجمنٹ',
    users: 'صارف کا انتظام',
    settings: 'سسٹم کی ترتیبات',
    logout: 'لاگ آؤٹ',
    system: 'سسٹم',
    management_portal: 'مینجمنٹ پورٹل',
    master_admin: 'ماسٹر ایڈمن',
    save_changes: 'تمام تبدیلیاں محفوظ کریں',
    saving: 'محفوظ ہو رہا ہے...',
    thank_you: 'کاروبار کے لئے آپ کا شکریہ!',
    invoice_to: 'انوائس برائے:',
    invoice_no: 'انوائس نمبر',
    name: 'نام',
    phone: 'فون',
    date: 'تاریخ',
    txn_id: 'ٹی ایکس این آئی ڈی',
    sl_no: 'سیریل نمبر',
    item_description: 'تفصیل',
    unit_price: 'یونٹ قیمت',
    quantity: 'مقدار',
    total: 'کل',
    bank_info: 'بینک کی معلومات',
    bank_name: 'بینک کا نام',
    branch_name: 'برانچ کا نام',
    account_no: 'اکاؤنٹ نمبر',
    payment_status: 'ادائیگی کی حیثیت',
    terms_condition: 'شرائط و ضوابط',
    sub_total: 'ذیلی کل',
    paid_amount: 'ادا شدہ رقم',
    due_balance: 'واجب الادا توازن',
    grand_total: 'مجموعی کل',
    scan_to_verify: 'تصدیق کے لیے اسکین کریں',
    welcome_back: 'آپ کے کام کی جگہ پر خوش آمدید',
    username: 'اسم صارف',
    password: 'پاس ورڈ',
    enter_username: 'اسم صارف درج کریں',
    enter_password: 'پاس ورڈ درج کریں',
    sign_in: 'سائن ان کریں',
    sign_in_google: 'گوگل کے ساتھ سائن ان کریں',
    invalid_credentials: 'غلط اسم صارف یا پاس ورڈ۔ admin / admin123 استعمال کریں',
    unexpected_error: 'ایک غیر متوقع غلطی واقع ہوئی ہے۔',
    paid: 'ادا شدہ',
    pending: 'زیر التواء',
    overdue: 'واجب الادا',
    unpaid_status: 'غیر ادا شدہ',
    time: 'وقت'
  },
  HI: {
    dashboard: 'डैशबोर्ड अवलोकन',
    invoices: 'चालान सूची',
    unpaid: 'अवैतनिक चालान',
    apps: 'ऐप प्रबंधन',
    panels: 'पैनल प्रबंधन',
    decoders: 'डिकोडर प्रबंधन',
    users: 'उपयोगकर्ता प्रबंधन',
    settings: 'सिस्टम सेटिंग्स',
    logout: 'लॉगआउट',
    system: 'सिस्टम',
    management_portal: 'प्रबंधन पोर्टल',
    master_admin: 'मास्टर एडमिन',
    save_changes: 'सभी परिवर्तन सहेजें',
    saving: 'सहेजा जा रहा है...',
    thank_you: 'आपके व्यवसाय के लिए धन्यवाद!',
    invoice_to: 'चालान सेवा में:',
    invoice_no: 'चालान संख्या',
    name: 'नाम',
    phone: 'फोन',
    date: 'तारीख',
    txn_id: 'लेनदेन आईडी',
    sl_no: 'क्रम संख्या',
    item_description: 'वस्तु विवरण',
    unit_price: 'इकाई मूल्य',
    quantity: 'मात्रा',
    total: 'कुल',
    bank_info: 'बैंक विवरण',
    bank_name: 'बैंक का नाम',
    branch_name: 'शाखा का नाम',
    account_no: 'खाता संख्या',
    payment_status: 'भुगतान की स्थिति',
    terms_condition: 'नियम और शर्तें',
    sub_total: 'उप-कुल',
    paid_amount: 'भुगतान की गई राशि',
    due_balance: 'बकाया राशि',
    grand_total: 'कुल योग',
    scan_to_verify: 'सत्यापित करने के लिए स्कैन करें',
    welcome_back: 'आपके वर्कस्पेस में स्वागत है',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    enter_username: 'उपयोगकर्ता नाम दर्ज करें',
    enter_password: 'पासवर्ड दर्ज करें',
    sign_in: 'साइन इन करें',
    sign_in_google: 'गूगल के साथ साइन इन करें',
    invalid_credentials: 'गलत उपयोगकर्ता नाम या पासवर्ड। admin / admin123 का उपयोग करें',
    unexpected_error: 'एक अप्रत्याशित त्रुटि हुई।',
    paid: 'भुगतान किया गया',
    pending: 'लंबित',
    overdue: 'विलंबित',
    unpaid_status: 'अवैतनिक',
    time: 'समय'
  },
  AR: {
    dashboard: 'نظرة عامة على لوحة القيادة',
    invoices: 'قائمة الفواتير',
    unpaid: 'فواتير غير مدفوعة',
    apps: 'إدارة التطبيقات',
    panels: 'إدارة اللوحات',
    decoders: 'إدارة أجهزة فك التشفير',
    users: 'إدارة المستخدمين',
    settings: 'إعدادات النظام',
    logout: 'تسجيل الخروج',
    system: 'النظام',
    management_portal: 'بوابة الإدارة',
    master_admin: 'إدارة ماستر',
    save_changes: 'حفظ جميع التغييرات',
    saving: 'جاري الحفظ...',
    thank_you: 'شكرا لتعاملكم معنا!',
    invoice_to: 'فاتورة إلى:',
    invoice_no: 'رقم الفاتورة',
    name: 'الاسم',
    phone: 'الهاتف',
    date: 'التاريخ',
    txn_id: 'رقم المعاملة',
    sl_no: 'الرقم التسلسلي',
    item_description: 'وصف البند',
    unit_price: 'سعر الوحدة',
    quantity: 'الكمية',
    total: 'المجموع',
    bank_info: 'معلومات البنك',
    bank_name: 'اسم البنك',
    branch_name: 'اسم الفرع',
    account_no: 'رقم الحساب',
    payment_status: 'حالة الدفع',
    terms_condition: 'الشروط والأحكام',
    sub_total: 'المجموع الفرعي',
    paid_amount: 'المبلغ المدفوع',
    due_balance: 'الرصيد المستحق',
    grand_total: 'المجموع الإجمالي',
    scan_to_verify: 'امسح للتحقق',
    finances: 'الاستثمارات',
    financial_overview: 'نظرة عامة مالية',
    financial_summary: 'ملخص إيرادات النظام وآخر السجلات',
    total_revenue: 'إجمالي الإيرادات',
    total_investment: 'إجمالي الاستثمار',
    net_profit: 'صافي الربح',
    pending_invoices_status: 'الفواتير المعلقة',
    system_health: 'صحة النظام',
    operational: 'تشغيلي',
    revenue_stream: 'تدفق الإيرادات',
    recent_invoices: 'الفواتير الأخيرة',
    recent_activities: 'الأنشطة الأخيرة',
    view_full_history: 'عرض السجل الكامل',
    no_invoices: 'لم يتم العثور على فواتير',
    invoice_management: 'إدارة الفواتير',
    billing_records_desc: 'الفواتير، السجلات، وتتبع المستحقات',
    unpaid_invoices_desc: 'عرض السجلات المعلقة والمتأخرة',
    create_new_invoice: 'إنشاء فاتورة جديدة',
    filter_invoices: 'تصفية الفواتير...',
    id_date: 'المعرف / التاريخ',
    source: 'المصدر',
    client_method: 'العميل / الطريقة',
    actions: 'الإجراءات',
    status: 'الحالة',
    generating_pdf: 'جاري إنشاء PDF...',
    please_wait_pdf: 'يرجى الانتظار بينما نجهز فاتورتك',
    invoice_preview: 'معاينة الفاتورة',
    prof_layout_desc: 'تنسيق احترافي للطباعة والمشاركة',
    download_pdf: 'تحميل PDF',
    preview_invoice: 'معاينة الفاتورة',
    edit_invoice: 'تعديل الفاتورة',
    delete_invoice: 'حذف الفاتورة',
    welcome_back: 'مرحباً بعودتك إلى مساحة العمل الخاصة بك',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    enter_username: 'أدخل اسم المستخدم',
    enter_password: 'أدخل كلمة المرور',
    sign_in: 'تسجيل الدخول',
    sign_in_google: 'تسجيل الدخول باستخدام جوجل',
    invalid_credentials: 'اسم المستخدم أو كلمة المرور غير صالحة. استخدم admin / admin123',
    unexpected_error: 'حدث خطأ غير متوقع.',
    no_recent_activities: 'لم يتم العثور على أنشطة أخيرة',
    understood: 'فهمت',
    invoice_gen_desc: 'إنشاء الفواتير مرتبط بطلبات العملاء.',
    paid: 'مدفوع',
    pending: 'قيد الانتظار',
    overdue: 'متأخر',
    unpaid_status: 'غير مدفوع',
    time: 'الوقت'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageBase] = useState<Language>(() => {
    return (localStorage.getItem('master_language') as Language) || 'EN';
  });

  const setLanguage = (lang: Language) => {
    setLanguageBase(lang);
    localStorage.setItem('master_language', lang);
    const isRTL = lang === 'AR' || lang === 'UR';
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = lang.toLowerCase();
  };

  useEffect(() => {
    const isRTL = language === 'AR' || language === 'UR';
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language.toLowerCase();
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || translations['EN'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
